### PR TITLE
1 unittests

### PR DESCRIPTION
**Pull request by christensonb**
This change is [Reviewable](https://reviewable.io/reviews/seaborngames/file/6)

### CODE REVIEW

**Comment by MichaelChristenson** [comment]
*[seaborn/__init__.py, line 0 at r3](https://reviewable.io:443/reviews/seaborngames/file/6#-L5_9WUmc8QwCFr9tztP:-L5_9WUmc8QwCFr9tztQ:b-bmdw7m) ([raw file](https://github.com/seaborngames/file/blob/b80e4dfbebef4f6b3d41b2c701b2e063d57d0f23/seaborn/__init__.py#L0)):*
Delete this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/6)*

**Comment by MichaelChristenson** [comment]
Reviewed 2 of 5 files at r1, 3 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/6)*

**Comment by christensonb** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[seaborn/__init__.py, line  at r3](https://reviewable.io:443/reviews/seaborngames/file/6#-L5_9WUmc8QwCFr9tztP:-L5_CbXKoJjyhni8pFqk:b-896fix) ([raw file](https://github.com/seaborngames/file/blob/b80e4dfbebef4f6b3d41b2c701b2e063d57d0f23/seaborn/__init__.py#L)):*
<details><summary><i>Previously, MichaelChristenson wrote…</i></summary><blockquote>

Delete this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/6)*

**Comment by MichaelChristenson** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/6)*

**Comment by MichaelChristenson** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/6#-:-L5_DFqr4EnociwfdgoN:bnfp4nl)*

**Pull request merged**
