### PR TITLE
Search

### PR DESCRIPTION
**Pull request by MichaelChristenson**
Established a search function and accompanying unit test; camel-cased the unit test class.

---
This change is [Reviewable](https://reviewable.io/reviews/seaborngames/file/4)

### CODE REVIEW

**Comment by christensonb** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[requirements.txt, line 0 at r1](https://reviewable.io:443/reviews/seaborngames/file/4#-L4UKOrpyJm_nJaNooFn:-L4UKOrpyJm_nJaNooFo:b53ures) ([raw file](https://github.com/seaborngames/file/blob/79936d3e9143d9f93bb69c8ec2fcf73f2a7e4a2e/requirements.txt#L0)):*
why is this empty

---

*[seaborn/__init__.py, line 0 at r1](https://reviewable.io:443/reviews/seaborngames/file/4#-L4UKRj3lOYW3UlWsd3O:-L4UKRj3lOYW3UlWsd3P:b55d2c1) ([raw file](https://github.com/seaborngames/file/blob/79936d3e9143d9f93bb69c8ec2fcf73f2a7e4a2e/seaborn/__init__.py#L0)):*
why is this here

---

*[seaborn/file/file.py, line 239 at r1](https://reviewable.io:443/reviews/seaborngames/file/4#-L4UHo0Yb8CCpWdWLfZQ:-L4UHo0Yb8CCpWdWLfZR:b-oia63y) ([raw file](https://github.com/seaborngames/file/blob/59bdd10971af675c7d2b7f9681cbe97fe17c3ceb/seaborn/file/file.py#L239)):*
> ```Python
> 
> 
> def find_item(target, from_path=None, depth_first=False):
> ```

why not find_file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/4)*

**Comment by christensonb** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/4)*

**Comment by christensonb** [comment]
you need to rebase this

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/4#-:-L5_ZlwplUv0aHUNIOLh:b-625ki7)*

**Comment by MichaelChristenson** [comment]
*[seaborn/file/file.py, line 239 at r1](https://reviewable.io:443/reviews/seaborngames/file/4#-L4UHo0Yb8CCpWdWLfZQ:-L5_pPoXvOP8aU-vg_ZQ:b-c5yfe4) ([raw file](https://github.com/seaborngames/file/blob/59bdd10971af675c7d2b7f9681cbe97fe17c3ceb/seaborn/file/file.py#L239)):*
<details><summary><i>Previously, christensonb (Ben Christenson) wrote…</i></summary><blockquote>

why not find_file
</blockquote></details>

Item may be a directory

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/4)*

**Comment by christensonb** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[seaborn/file/file.py, line 239 at r1](https://reviewable.io:443/reviews/seaborngames/file/4#-L4UHo0Yb8CCpWdWLfZQ:-L5_wAvE1Ru3kV6y5CEc:b-93miqr) ([raw file](https://github.com/seaborngames/file/blob/59bdd10971af675c7d2b7f9681cbe97fe17c3ceb/seaborn/file/file.py#L239)):*
<details><summary><i>Previously, MichaelChristenson wrote…</i></summary><blockquote>

Item may be a directory
</blockquote></details>

change it to find_path then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/4)*

**Pull request closed without merging**
