### PR TITLE
Unittests established

### PR DESCRIPTION
**Pull request by MichaelChristenson**
This change is [Reviewable](https://reviewable.io/reviews/seaborngames/file/2)

### CODE REVIEW

**Comment by christensonb** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/hello.wrld, line 1 at r1](https://reviewable.io:443/reviews/seaborngames/file/2#-L2YgxzBTSgdpjRMVk0e:-L2YgxzBTSgdpjRMVk0f:b-n8zoqr) ([raw file](https://github.com/seaborngames/file/blob/4f43f963753342cddb5aeca3eaad7143b327fdce/test/hello.wrld#L1)):*
> ```
> Hello
> ```

what is this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/2)*

**Comment by MichaelChristenson** [comment]
*[test/hello.wrld, line 1 at r1](https://reviewable.io:443/reviews/seaborngames/file/2#-L2YgxzBTSgdpjRMVk0e:-L2b9taHOeV9gSRFCeOD:bu1puu7) ([raw file](https://github.com/seaborngames/file/blob/4f43f963753342cddb5aeca3eaad7143b327fdce/test/hello.wrld#L1)):*
<details><summary><i>Previously, christensonb (Ben Christenson) wrote…</i></summary><blockquote>

what is this
</blockquote></details>

It's a dummy file. Used in testing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/2)*

**Comment by christensonb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/hello.wrld, line 1 at r1](https://reviewable.io:443/reviews/seaborngames/file/2#-L2YgxzBTSgdpjRMVk0e:-L2kdPn8AVTevnU9KaMx:bpsdzpn) ([raw file](https://github.com/seaborngames/file/blob/4f43f963753342cddb5aeca3eaad7143b327fdce/test/hello.wrld#L1)):*
<details><summary><i>Previously, MichaelChristenson wrote…</i></summary><blockquote>

It's a dummy file. Used in testing.
</blockquote></details>

if it is a data file for the test, then put it in test/data
if it is a prodcut of the test then delete it after the test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/2)*

**Comment by christensonb** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[requirements.txt, line 0 at r2](https://reviewable.io:443/reviews/seaborngames/file/2#-L3Pn3mRTvAn51TwylNh:-L3Pn3mS8lKbP5L5M4RW:byywrhq) ([raw file](https://github.com/seaborngames/file/blob/48a8b54e19c38d9774b5e296d00a2658898e7d64/requirements.txt#L0)):*
why is this here, we should either populate it or remove it

---

*[seaborn/__init__.py, line 0 at r2](https://reviewable.io:443/reviews/seaborngames/file/2#-L3Pn7Nl7WLtlNF5ZRwM:-L3Pn7Nl7WLtlNF5ZRwN:b7slcur) ([raw file](https://github.com/seaborngames/file/blob/48a8b54e19c38d9774b5e296d00a2658898e7d64/seaborn/__init__.py#L0)):*
this should be removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/2)*

**Comment by christensonb** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/file/2#-:-L5ZwLogWffG5g-5tFG6:bnfp4nl)*

**Pull request closed without merging**
